"""Added Hotel Booking Model 5

Revision ID: 212efa4a8794
Revises: 763b04a42d51
Create Date: 2025-03-23 07:03:27.975635

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '212efa4a8794'
down_revision = '763b04a42d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrappeditem', 'price_agoda',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('scrappeditem', 'url_agoda',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrappeditem', 'url_agoda',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('scrappeditem', 'price_agoda',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
