"""Added Hotel Booking Model 3

Revision ID: 21889a111446
Revises: ed40f37d8b82
Create Date: 2025-03-23 04:14:17.375784

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21889a111446'
down_revision = 'ed40f37d8b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
