"""Added Hotel Booking Model 6

Revision ID: 60832e981f98
Revises: 212efa4a8794
Create Date: 2025-03-23 19:13:27.130858

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '60832e981f98'
down_revision = '212efa4a8794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
