"""Added Hotel Booking Model 4

Revision ID: 763b04a42d51
Revises: 8872419d40e8
Create Date: 2025-03-23 04:29:24.043990

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '763b04a42d51'
down_revision = '8872419d40e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
