"""Added Hotel Booking Model 4

Revision ID: 8872419d40e8
Revises: 21889a111446
Create Date: 2025-03-23 04:25:43.914440

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8872419d40e8'
down_revision = '21889a111446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
