"""Added Hotel Booking Model

Revision ID: 9726c0306050
Revises: 1a31ce608336
Create Date: 2025-03-23 03:45:41.777863

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9726c0306050'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrappeditemshistory',
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('stars', sa.Float(), nullable=True),
    sa.Column('scrape_status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scrapped_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrappeditem',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('price_booking', sa.Float(), nullable=False),
    sa.Column('url_booking', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('stars', sa.Float(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price_agoda', sa.Float(), nullable=False),
    sa.Column('url_agoda', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['scrappeditemshistory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarkedscrappeditem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('bookmarked_at', sa.DateTime(), nullable=False),
    sa.Column('scrapped_item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrapped_item_id'], ['scrappeditem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarkedscrappeditem')
    op.drop_table('scrappeditem')
    op.drop_table('scrappeditemshistory')
    # ### end Alembic commands ###
