"""Added Hotel Booking Model 2

Revision ID: ed40f37d8b82
Revises: 9726c0306050
Create Date: 2025-03-23 03:55:50.680660

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ed40f37d8b82'
down_revision = '9726c0306050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
